### ISSUE TITLE
AptX Adaptive support

### ISSUE THREAD

**Issue by crocket** [Arkq/openaptx#1]
Is it supported already?

**Comment by Arkq** [comment]
No, there is no support for AptX Adaptive. There are two things required in order to properly reverse-engineer such functionality. Encoder library (ARM or x86), and device which supports such encoding (for testing). Unfortunately, I've got none... So, the first step will be to get library to work with (e.g. from some smartphone root file system).

**Comment by leleobhz** [comment]
@Arkq This issue still missing binaries or there is any progress in this issue?

**Comment by Arkq** [comment]
Yes, I've got no binaries for that. I'm collecting all available binaries as an archive, here: https://github.com/Arkq/openaptx/tree/master/archive

**Comment by crocket** [comment]
Closing it because I don't use bluetooth anymore.
