### ISSUE TITLE
Same Header Name

### ISSUE THREAD

**Issue by kicker0429** [Arkq/openaptx#6]
Unless I missed a configuration option, it appears that your header and libopenaptx's are both openaptx.h.  Obviously, this means that one cannot have both packages installed simultaneously.

**Comment by Arkq** [comment]
Yes, these headers are conflicting so it is not possible to install both these libraries (in a default location). However, in most cases you do not want to have both. Either you are using libopenaptx (which is fully open-source), or you are using this repo (openaptx) because you want to use Qualcomm aptX API in your project.
